# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"2\n\x0fRegisterRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"G\n\x12SendMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x82\x01\n\x0b\x43hatService\x12\x39\n\x12RegisterConnection\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12\x38\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=14
  _globals['_REGISTERREQUEST']._serialized_end=64
  _globals['_REGISTERRESPONSE']._serialized_start=66
  _globals['_REGISTERRESPONSE']._serialized_end=100
  _globals['_SENDMESSAGEREQUEST']._serialized_start=102
  _globals['_SENDMESSAGEREQUEST']._serialized_end=173
  _globals['_SENDMESSAGERESPONSE']._serialized_start=175
  _globals['_SENDMESSAGERESPONSE']._serialized_end=212
  _globals['_CHATSERVICE']._serialized_start=215
  _globals['_CHATSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
